/** Nombres de permisos definidos en el backend (PermisoSeeder). */
export const PERMISOS = {
  usuarios: {
    listar: 'usuarios.listar',
    crear: 'usuarios.crear',
    ver: 'usuarios.ver',
    editar: 'usuarios.editar',
    eliminar: 'usuarios.eliminar',
    restaurar: 'usuarios.restaurar',
  },
  operadores: {
    listar: 'operadores.listar',
    crear: 'operadores.crear',
    ver: 'operadores.ver',
    editar: 'operadores.editar',
    eliminar: 'operadores.eliminar',
    restaurar: 'operadores.restaurar',
  },
  roles: {
    listar: 'roles.listar',
  },
  permisos: {
    listar: 'permisos.listar',
  },
  catalogos: {
    listar: 'catalogos.listar',
  },
  prestadores: {
    listar: 'prestadores.listar',
    crear: 'prestadores.crear',
    ver: 'prestadores.ver',
    editar: 'prestadores.editar',
    eliminar: 'prestadores.eliminar',
    restaurar: 'prestadores.restaurar',
  },
  especialidades: {
    listar: 'especialidades.listar',
    crear: 'especialidades.crear',
    ver: 'especialidades.ver',
    editar: 'especialidades.editar',
    eliminar: 'especialidades.eliminar',
    restaurar: 'especialidades.restaurar',
  },
  portafolio: {
    listar: 'portafolio.listar',
    crear: 'portafolio.crear',
    editar: 'portafolio.editar',
    eliminar: 'portafolio.eliminar',
  },
  especialistas: {
    listar: 'especialistas.listar',
    crear: 'especialistas.crear',
    ver: 'especialistas.ver',
    editar: 'especialistas.editar',
    eliminar: 'especialistas.eliminar',
    restaurar: 'especialistas.restaurar',
    importar: 'especialistas.importar',
  },
  entidades: {
    listar: 'entidades.listar',
    crear: 'entidades.crear',
    ver: 'entidades.ver',
    editar: 'entidades.editar',
    eliminar: 'entidades.eliminar',
    restaurar: 'entidades.restaurar',
  },
  contratos: {
    listar: 'contratos.listar',
    crear: 'contratos.crear',
    ver: 'contratos.ver',
    editar: 'contratos.editar',
    eliminar: 'contratos.eliminar',
    restaurar: 'contratos.restaurar',
  },
  poblaciones: {
    listar: 'poblaciones.listar',
    crear: 'poblaciones.crear',
    ver: 'poblaciones.ver',
    editar: 'poblaciones.editar',
    eliminar: 'poblaciones.eliminar',
    restaurar: 'poblaciones.restaurar',
    cargar: 'poblaciones.cargar',
  },
  ordenes: {
    listar: 'ordenes.listar',
    ver: 'ordenes.ver',
    crear: 'ordenes.crear',
    gestionar: 'ordenes.gestionar',
  },
  preanestesia: {
    configurar: 'preanestesia.configurar',
  },
  citas: {
    listar: 'citas.listar',
  },
  historias: {
    listar: 'historias.listar',
    ver: 'historias.ver',
    diligenciar: 'historias.diligenciar',
    anular: 'historias.anular',
  },
  programacion: {
    listar: 'programacion.listar',
    generar: 'programacion.generar',
    aprobar: 'programacion.aprobar',
    realizar: 'programacion.realizar',
  },
  inventario: {
    listar: 'inventario.listar',
    gestionar: 'inventario.gestionar',
  },
  integraciones: {
    gestionar: 'integraciones.gestionar',
  },
  agendas: {
    listar: 'agendas.listar',
    gestionar: 'agendas.gestionar',
  },
  sedes: {
    listar: 'sedes.listar',
    crear: 'sedes.crear',
    ver: 'sedes.ver',
    editar: 'sedes.editar',
    eliminar: 'sedes.eliminar',
    restaurar: 'sedes.restaurar',
  },
  tiposDocumento: {
    listar: 'tipos_documento.listar',
  },
} as const;
